version: '3'

services:
    web:
        image: nginx
        volumes: 
          - ./config/${PORTAINER_EDGE_ID}:/tmp/config
          - ./config/${PORTAINER_EDGE_ID}.yml:/tmp/${PORTAINER_EDGE_ID}.yml
          - ./config/${PORTAINER_EDGE_GROUP}:/tmp/config_grp
          - ./config/${PORTAINER_EDGE_GROUP}.yml:/tmp/${PORTAINER_EDGE_GROUP}.yml
